### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by f2u39** [f2u39/ditto-react#1]
- [x] Transfer JavaScript to TypeScript
- [x] Transfer Bootstrap to MUI
- [x] Change themes button in AppBar
